# -*- coding: utf-8 -*-
"""CNN Fashion MNSIT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqO4K3lqpwnPVwhqznA5H28x6qeiLnMf
"""

#the fashion dataset has 28x28 grey scale images
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input,Conv2D,Dense,Flatten,Dropout
from tensorflow.keras.models import Model
import tensorflow as tf

fashion_mnist_data=tf.keras.datasets.fashion_mnist
(x_train,y_train),(x_test,y_test)=fashion_mnist_data.load_data()
x_train,x_test=x_train/255.0,x_test/255.0
print(x_train.shape)

#let us find out the number of classes.We can simply find the no of unique values in targets of training dataset
K=len(set(y_train))
print("Number of classes is ",K)
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
print(x_train.shape)

#Let us build the model
i=Input(shape=x_train[0].shape)
x=Conv2D(32,(3,3),strides=2,activation='relu')(i)
x=Conv2D(64,(3,3),strides=2,activation='relu')(x)
x=Conv2D(128,(3,3),strides=2,activation='relu')(x)
x=Flatten()(x)
x=Dropout(0.2)(x)
x=Dense(512,activation='relu')(x)
x=Dropout(0.2)(x)
x=Dense(K,activation='softmax')(x)

model=Model(i,x)

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

no_of_epochs=20
r=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=no_of_epochs)

model.evaluate(x_train,y_train)

model.evaluate(x_test,y_test)

